### ISSUE TITLE
Update plugins vession 1.19.50 2.9.0 pls

### ISSUE THREAD

**Issue by HoLyMosquito487** [kkj9333/Virtual-Box#1]

**Comment by kkj9333** [comment]
sorry, the SDK of liteloaderBDS hasn't update, so we can't update now, too.

**Comment by HoLyMosquito487** [comment]
Thanks for browsing.  when LiteLoader update, update the plugin.  thank

**Comment by kkj9333** [comment]
ok

**Comment by HoLyMosquito487** [comment]
i don't understand why the data player sometimes loses data to 0kb.  then do not create enchant chest (1.19.30 error). Virbox in version 1.19.40. Hope you can fix it in the next version

**Comment by HoLyMosquito487** [comment]
When the data player reaches 0kb when writing the command, it will crash the server

**Comment by HoLyMosquito487** [comment]
do you use QQ can i make friends with you so we can exchange

**Comment by kkj9333** [comment]
> i don't understand why the data player sometimes loses data to 0kb. then do not create enchant chest (1.19.30 error). Virbox in version 1.19.40. Hope you can fix it in the next version

Do you have any means of reproduction？

**Comment by kkj9333** [comment]
> do you use QQ can i make friends with you so we can exchange

Well, you can join QQ group:379178988

**Comment by HoLyMosquito487** [comment]
axolotl in bucket? Is that the reason?

**Comment by kkj9333** [comment]
> axolotl in bucket? Is that the reason?
I just tried It won't lead to mistakes

**Comment by kkj9333** [comment]
> When the data player reaches 0kb when writing the command, it will crash the server

How? show me the picture.

**Comment by HoLyMosquito487** [comment]
okay. thanks

**Comment by HoLyMosquito487** [comment]
[Crashed!]
-- Unhandled Exception in -> ucrtbase.dll
-- Exception Code: 0xC0000409
-- C++ STL Exception detected!

[StackTrace] Function abort at 0x7FF8192AE9D0  [ucrtbase.dll<6.2.14393.0>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF8192AEA1E  [ucrtbase.dll<6.2.14393.0>]
[StackTrace] Function terminate at 0x7FF8192AE0A0  [ucrtbase.dll<6.2.14393.0>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF8192AE0BF  [ucrtbase.dll<6.2.14393.0>]
[StackTrace] Function _NLG_Return2 at 0x7FF80EE81150  [VCRUNTIME140_1.dll<14.29.30139.0>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF80EE81AAB  [VCRUNTIME140_1.dll<14.29.30139.0>]
[StackTrace] Function _NLG_Return2 at 0x7FF80EE81150  [VCRUNTIME140_1.dll<14.29.30139.0>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF80EE82317  [VCRUNTIME140_1.dll<14.29.30139.0>]
[StackTrace] Function _CxxFrameHandler4 at 0x7FF80EE84030  [VCRUNTIME140_1.dll<14.29.30139.0>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF80EE840D9  [VCRUNTIME140_1.dll<14.29.30139.0>]
[StackTrace] Function _chkstk at 0x7FF81BE5AA80  [ntdll.dll<6.2.14393.479>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF81BE5AB9D  [ntdll.dll<6.2.14393.479>]
[StackTrace] Function RtlImageNtHeaderEx at 0x7FF81BDF9490  [ntdll.dll<6.2.14393.479>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF81BDF9913  [ntdll.dll<6.2.14393.479>]
[StackTrace] Function KiUserExceptionDispatcher at 0x7FF81BE59C80  [ntdll.dll<6.2.14393.479>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF81BE59CBA  [ntdll.dll<6.2.14393.479>]
[StackTrace] Function RaiseException at 0x7FF8184F7720  [KERNELBASE.dll<6.2.14393.479>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF8184F7788  [KERNELBASE.dll<6.2.14393.479>]
[StackTrace] Function CxxThrowException at 0x7FF8104063F0  [VCRUNTIME140.dll<14.29.30139.0>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF810406480  [VCRUNTIME140.dll<14.29.30139.0>]
[StackTrace] Function onPostInit at 0x7FF801E3B530  [Virtual_box.dll]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF801E4D3BD  [Virtual_box.dll]
[StackTrace] Function onPostInit at 0x7FF801E3B530  [Virtual_box.dll]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF801E46FBA  [Virtual_box.dll]
[StackTrace] Function onPostInit at 0x7FF801E3B530  [Virtual_box.dll]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF801E57888  [Virtual_box.dll]
[StackTrace] Function onPostInit at 0x7FF801E3B530  [Virtual_box.dll]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF801E5B8C4  [Virtual_box.dll]
[StackTrace] Function ???????? at 0x7FF801E2F359  [Virtual_box.dll]
[StackTrace] Function ???????? at 0x7FF801E26CA7  [Virtual_box.dll]
[StackTrace] Function onPostInit at 0x7FF801E3B530  [Virtual_box.dll]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF801E3F53D  [Virtual_box.dll]
[StackTrace] Function Packet::handle at 0x7FF77D5156E0  [bedrock_server_mod.exe<1.19.41.01>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF77D5156FA  [bedrock_server_mod.exe<1.19.41.01>]
[StackTrace] Function NetworkHandler::_sortAndPacketizeEvents at 0x7FF77D1E9700  [bedrock_server_mod.exe<1.19.41.01>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF77D1E9D19  [bedrock_server_mod.exe<1.19.41.01>]
[StackTrace] Function <lambda_f5fb18606e7a5aecb19e8d1571e0892d>::operator() at 0x7FF77D1E81E0  [bedrock_server_mod.exe<1.19.41.01>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF77D1E84CF  [bedrock_server_mod.exe<1.19.41.01>]
[StackTrace] Function NetworkHandler::runEvents at 0x7FF77D1EC740  [bedrock_server_mod.exe<1.19.41.01>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF77D1EC851  [bedrock_server_mod.exe<1.19.41.01>]
[StackTrace] Function Minecraft::update at 0x7FF77D642B20  [bedrock_server_mod.exe<1.19.41.01>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF77D643E79  [bedrock_server_mod.exe<1.19.41.01>]
[StackTrace] Function ServerInstance::_update at 0x7FF77D648DC0  [bedrock_server_mod.exe<1.19.41.01>]
-- At File (null) : Line 0 
[StackTrace] Function ???????? at 0x7FF77D648EBD  [bedrock_server_mod.exe<1.19.41.01>]
[StackTrace] Function ???????? at 0x7FFF974274D9  []

**Comment by kkj9333** [comment]
> [Crashed!] -- Unhandled Exception in -> ucrtbase.dll -- Exception Code: 0xC0000409 -- C++ STL Exception detected!
> 
> [StackTrace] Function abort at 0x7FF8192AE9D0 [ucrtbase.dll<6.2.14393.0>] -- At File (null) : Line 0 [StackTrace] Function ???????? at 0x7FF8192AEA1E [ucrtbase.dll<6.2.14393.0>] [StackTrace] Function terminate at 0x7FF8192AE0A0 [ucrtbase.dll<6.2.14393.0>] -- At File (null) : Line 0 [StackTrace] Function ???????? at 0x7FF8192AE0BF [ucrtbase.dll<6.2.14393.0>] [StackTrace] Function _NLG_Return2 at 0x7FF80EE81150 [VCRUNTIME140_1.dll<14.29.30139.0>] -- At File (null) : Line 0 [StackTrace] Function ???????? at 0x7FF80EE81AAB [VCRUNTIME140_1.dll<14.29.30139.0>] [StackTrace] Function _NLG_Return2 at 0x7FF80EE81150 [VCRUNTIME140_1.dll<14.29.30139.0>] -- At File (null) : Line 0 [StackTrace] Function ???????? at 0x7FF80EE82317 [VCRUNTIME140_1.dll<14.29.30139.0>] [StackTrace] Function _CxxFrameHandler4 at 0x7FF80EE84030 [VCRUNTIME140_1.dll<14.29.30139.0>] -- At File (null) : Line 0 [StackTrace] Function ???????? at 0x7FF80EE840D9 [VCRUNTIME140_1.dll<14.29.30139.0>] [StackTrace] Function _chkstk at 0x7FF81BE5AA80 [ntdll.dll<6.2.14393.479>] -- At File (null) : Line 0 [StackTrace] Function ???????? at 0x7FF81BE5AB9D [ntdll.dll<6.2.14393.479>] [StackTrace] Function RtlImageNtHeaderEx at 0x7FF81BDF9490 [ntdll.dll<6.2.14393.479>] -- At File (null) : Line 0 [StackTrace] Function ???????? at 0x7FF81BDF9913 [ntdll.dll<6.2.14393.479>] [StackTrace] Function KiUserExceptionDispatcher at 0x7FF81BE59C80 [ntdll.dll<6.2.14393.479>] -- At File (null) : Line 0 [StackTrace] Function ???????? at 0x7FF81BE59CBA [ntdll.dll<6.2.14393.479>] [StackTrace] Function RaiseException at 0x7FF8184F7720 [KERNELBASE.dll<6.2.14393.479>] -- At File (null) : Line 0 [StackTrace] Function ???????? at 0x7FF8184F7788 [KERNELBASE.dll<6.2.14393.479>] [StackTrace] Function CxxThrowException at 0x7FF8104063F0 [VCRUNTIME140.dll<14.29.30139.0>] -- At File (null) : Line 0 [StackTrace] Function ???????? at 0x7FF810406480 [VCRUNTIME140.dll<14.29.30139.0>] [StackTrace] Function onPostInit at 0x7FF801E3B530 [Virtual_box.dll] -- At File (null) : Line 0 [StackTrace] Function ???????? at 0x7FF801E4D3BD [Virtual_box.dll] [StackTrace] Function onPostInit at 0x7FF801E3B530 [Virtual_box.dll] -- At File (null) : Line 0 [StackTrace] Function ???????? at 0x7FF801E46FBA [Virtual_box.dll] [StackTrace] Function onPostInit at 0x7FF801E3B530 [Virtual_box.dll] -- At File (null) : Line 0 [StackTrace] Function ???????? at 0x7FF801E57888 [Virtual_box.dll] [StackTrace] Function onPostInit at 0x7FF801E3B530 [Virtual_box.dll] -- At File (null) : Line 0 [StackTrace] Function ???????? at 0x7FF801E5B8C4 [Virtual_box.dll] [StackTrace] Function ???????? at 0x7FF801E2F359 [Virtual_box.dll] [StackTrace] Function ???????? at 0x7FF801E26CA7 [Virtual_box.dll] [StackTrace] Function onPostInit at 0x7FF801E3B530 [Virtual_box.dll] -- At File (null) : Line 0 [StackTrace] Function ???????? at 0x7FF801E3F53D [Virtual_box.dll] [StackTrace] Function Packet::handle at 0x7FF77D5156E0 [bedrock_server_mod.exe<1.19.41.01>] -- At File (null) : Line 0 [StackTrace] Function ???????? at 0x7FF77D5156FA [bedrock_server_mod.exe<1.19.41.01>] [StackTrace] Function NetworkHandler::_sortAndPacketizeEvents at 0x7FF77D1E9700 [bedrock_server_mod.exe<1.19.41.01>] -- At File (null) : Line 0 [StackTrace] Function ???????? at 0x7FF77D1E9D19 [bedrock_server_mod.exe<1.19.41.01>] [StackTrace] Function <lambda_f5fb18606e7a5aecb19e8d1571e0892d>::operator() at 0x7FF77D1E81E0 [bedrock_server_mod.exe<1.19.41.01>] -- At File (null) : Line 0 [StackTrace] Function ???????? at 0x7FF77D1E84CF [bedrock_server_mod.exe<1.19.41.01>] [StackTrace] Function NetworkHandler::runEvents at 0x7FF77D1EC740 [bedrock_server_mod.exe<1.19.41.01>] -- At File (null) : Line 0 [StackTrace] Function ???????? at 0x7FF77D1EC851 [bedrock_server_mod.exe<1.19.41.01>] [StackTrace] Function Minecraft::update at 0x7FF77D642B20 [bedrock_server_mod.exe<1.19.41.01>] -- At File (null) : Line 0 [StackTrace] Function ???????? at 0x7FF77D643E79 [bedrock_server_mod.exe<1.19.41.01>] [StackTrace] Function ServerInstance::_update at 0x7FF77D648DC0 [bedrock_server_mod.exe<1.19.41.01>] -- At File (null) : Line 0 [StackTrace] Function ???????? at 0x7FF77D648EBD [bedrock_server_mod.exe<1.19.41.01>] [StackTrace] Function ???????? at 0x7FFF974274D9 []

I means the picture of 0KB file of virbox... just open it

**Comment by HoLyMosquito487** [comment]
![image](https://user-images.githubusercontent.com/104082600/205280423-8c7f5d0e-d6df-4365-9d44-586b828775d0.png)

**Comment by kkj9333** [comment]
> 

It is impossible to generate such data files under normal circumstances. It is recommended that you delete this file, and then virbox will regenerate a complete new file; Then please use the virbox plug-in I sent. If an error occurs again, please tell me immediately

**Comment by kkj9333** [comment]
> ![image](https://user-images.githubusercontent.com/104082600/205280423-8c7f5d0e-d6df-4365-9d44-586b828775d0.png)

It is impossible to generate such data files under normal circumstances. It is recommended that you delete this file, and then virbox will regenerate a complete new file; Then please use the virbox plug-in I sent. If an error occurs again, please tell me immediately

**Comment by kkj9333** [comment]
[Virtual_box.zip](https://github.com/kkj9333/Virtual-Box/files/10140627/Virtual_box.zip)
just use this.

**Comment by HoLyMosquito487** [comment]
I watched your video, it's quite normal, try resetting the server to see if you lose data

**Comment by HoLyMosquito487** [comment]
ah but you have to put axolotl in virbox and then turn it off, not put it in and out

**Comment by kkj9333** [comment]
It is reasonable. If it leads to a crash, it may be the problem caused by character encoding

**Comment by kkj9333** [comment]
OK, I will check it.

**Comment by HoLyMosquito487** [comment]
tks

**Comment by kkj9333** [comment]
> 

the mistake has been fixed. just dowload the latest virbox file.

**Comment by HoLyMosquito487** [comment]
okay

**Comment by kkj9333** [comment]
OK, maybe you can test 1.19.50 for this plugin:
https://github.com/kkj9333/Virtual-Box/releases/tag/BETA8-test8

**Comment by kkj9333** [comment]
the Beta version has been updated
