### ISSUE TITLE
建议增加直接自定义每层解锁价格的配置设置

### ISSUE THREAD

**Issue by chigdhuu** [kkj9333/Virtual-Box#2]
用公式计算价格有点麻烦，不是很灵活，而且一般服主也不会让解锁很多层背包，最多10层，希望可以让我们选择直接定义每层的解锁价格而不是用公式定义

**Comment by kkj9333** [comment]
能否举个例子来表示你想要设置的每层背包的价格？

**Comment by chigdhuu** [comment]
我想第一层设置4w，第二层设置2w，第三曾设置20w

**Comment by kkj9333** [comment]
我有一个主意，假定你说的第一层是指解锁时的page为0的页，你可以在配置文件设置公式为：
```javascript
    "paycalculationformula": "0-({page}-1)*({page}-2)*({page}-3)*40000/6+{page}*({page}-2)*({page}-3)*20000/2-{page}*({page}-1)*({page}-3)*200000/2",
```
这样就可以解决你的问题了

**Comment by kkj9333** [comment]
> 用公式计算价格有点麻烦，不是很灵活，而且一般服主也不会让解锁很多层背包，最多10层，希望可以让我们选择直接定义每层的解锁价格而不是用公式定义

这个也可以通过公式实现的

**Comment by kkj9333** [comment]
这里设置每页价格有个公式，假设你总共要设置n页（即maxpage=n），你想要设置解锁第i+1页的价格为x（请注意i+1应当小于等于n，i应当大于等于0），那你此处应设置的代数式P:
- 1. 设多项式F=({page}-0)*({page}-1)*({page}-2)*...*({page}-n+1)*({page}-n)，其中不包括({page}-i)；
- 2. 设多项式G=(-1)^(n-i)*x/((1*2*...*i)*(1*2*...*(n-i)))，请注意当i等于0时，1*2*...*i=1（0!=1）；
- 3. 则P=F*x/G，将i，n带入此式即得所求代数式P。
举个例子，当我总共要设置3页（即maxpage=3），则
我想要解锁第1页（即i=0）的价格为40000，此处代数式为-({page}-1)*({page}-2)*({page}-3)*40000/6；
我想要解锁第2页（即i=1）的价格为20000，此处代数式为({page}-0)*({page}-1)*({page}-3)*20000/2；
我想要解锁第3页（即i=2）的价格为200000，此处代数式为-({page}-0)*({page}-1)*({page}-2)*200000/2；
那么我应该设置的 "paycalculationformula": "0-({page}-1)*({page}-2)*({page}-3)*40000/6+{page}*({page}-2)*({page}-3)*20000/2-{page}*({page}-1)*({page}-3)*200000/2"
**这里的乘号被github省略了，请看下图：**
![image](https://user-images.githubusercontent.com/51207072/218912127-5533ab38-1a12-46c3-b4d5-a7ec91022aad.png)
