### ISSUE TITLE
1.19.71.02 Errors

### ISSUE THREAD

**Issue by nerd-king** [kkj9333/Virtual-Box#3]
Can't start with plugin installed:

```
06:51:24 ERROR [PreLoader] Could not find function in memory: ?remove@CompoundTag@@QEAA_NV?$basic_string_span@$$CBD$0?0@gsl@@@Z
06:51:24 ERROR [PreLoader] Plugin: Virtual_box.dll
06:51:24 ERROR [PreLoader] Could not find function in memory: ?get@CompoundTag@@QEBAPEBVTag@@V?$basic_string_span@$$CBD$0?0@gsl@@@Z
06:51:24 ERROR [PreLoader] Plugin: Virtual_box.dll
```

**Comment by kkj9333** [comment]
Sorry, LL's sdk has not been updated

**Comment by nerd-king** [comment]
> Sorry, LL's sdk has not been updated

Got it, I see they are still working through this latest release, thanks for responding.

**Comment by kkj9333** [comment]
https://github.com/kkj9333/Virtual-Box/releases/tag/BETA12_1
Hello, you can try it here (should also support 1.19.71).

**Comment by nerd-king** [comment]
Looks like it's working good again.  Do you have any plans to open the source for this? I have some ideas that could be nice to add to something like this, but alas no source.

**Comment by kkj9333** [comment]
> Looks like it's working good again. Do you have any plans to open the source for this? I have some ideas that could be nice to add to something like this, but alas no source.

What do you have in mind? This project is still private, but if you have a good idea, you can become a member.
